#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinanceManagement
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="HQData")]
	public partial class HQDataDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertQuotationSynthetic(QuotationSynthetic instance);
    partial void UpdateQuotationSynthetic(QuotationSynthetic instance);
    partial void DeleteQuotationSynthetic(QuotationSynthetic instance);
    partial void InsertMMFee(MMFee instance);
    partial void UpdateMMFee(MMFee instance);
    partial void DeleteMMFee(MMFee instance);
    partial void InsertMMSale(MMSale instance);
    partial void UpdateMMSale(MMSale instance);
    partial void DeleteMMSale(MMSale instance);
    partial void InsertMMRevenue(MMRevenue instance);
    partial void UpdateMMRevenue(MMRevenue instance);
    partial void DeleteMMRevenue(MMRevenue instance);
    partial void InsertMMFeeStruct(MMFeeStruct instance);
    partial void UpdateMMFeeStruct(MMFeeStruct instance);
    partial void DeleteMMFeeStruct(MMFeeStruct instance);
    partial void InsertMMFeeMaster(MMFeeMaster instance);
    partial void UpdateMMFeeMaster(MMFeeMaster instance);
    partial void DeleteMMFeeMaster(MMFeeMaster instance);
    partial void InsertMMFeeTypeStruct(MMFeeTypeStruct instance);
    partial void UpdateMMFeeTypeStruct(MMFeeTypeStruct instance);
    partial void DeleteMMFeeTypeStruct(MMFeeTypeStruct instance);
    #endregion
		
		public HQDataDataContext() : 
				base(global::FinanceManagement.Properties.Settings.Default.HQDataConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public HQDataDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public HQDataDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public HQDataDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public HQDataDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<QuotationSynthetic> QuotationSynthetics
		{
			get
			{
				return this.GetTable<QuotationSynthetic>();
			}
		}
		
		public System.Data.Linq.Table<MMFee> MMFees
		{
			get
			{
				return this.GetTable<MMFee>();
			}
		}
		
		public System.Data.Linq.Table<MMSale> MMSales
		{
			get
			{
				return this.GetTable<MMSale>();
			}
		}
		
		public System.Data.Linq.Table<MMRevenue> MMRevenues
		{
			get
			{
				return this.GetTable<MMRevenue>();
			}
		}
		
		public System.Data.Linq.Table<MMFeeStruct> MMFeeStructs
		{
			get
			{
				return this.GetTable<MMFeeStruct>();
			}
		}
		
		public System.Data.Linq.Table<MMFeeMaster> MMFeeMasters
		{
			get
			{
				return this.GetTable<MMFeeMaster>();
			}
		}
		
		public System.Data.Linq.Table<MMFeeTypeStruct> MMFeeTypeStructs
		{
			get
			{
				return this.GetTable<MMFeeTypeStruct>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.QuotationSynthetic")]
	public partial class QuotationSynthetic : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private System.Nullable<short> _QuotationNoYear;
		
		private System.Nullable<int> _QuotationNoOrder;
		
		private string _OrderCode;
		
		private System.Nullable<System.DateTime> _MadeTime;
		
		private string _CustomerName;
		
		private string _WorkPlace;
		
		private string _WorkName;
		
		private System.Nullable<int> _MaterialCostTotal;
		
		private System.Nullable<int> _WorkCostTotal;
		
		private System.Nullable<int> _OverheadExpenseTotal;
		
		private System.Nullable<int> _DiscountTotal;
		
		private System.Nullable<int> _AmountTotal;
		
		private System.Nullable<int> _AmountRecorded;
		
		private System.Nullable<System.DateTime> _PaidTime;
		
		private System.Nullable<char> _WorkType;
		
		private string _Remark;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnQuotationNoYearChanging(System.Nullable<short> value);
    partial void OnQuotationNoYearChanged();
    partial void OnQuotationNoOrderChanging(System.Nullable<int> value);
    partial void OnQuotationNoOrderChanged();
    partial void OnOrderCodeChanging(string value);
    partial void OnOrderCodeChanged();
    partial void OnMadeTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnMadeTimeChanged();
    partial void OnCustomerNameChanging(string value);
    partial void OnCustomerNameChanged();
    partial void OnWorkPlaceChanging(string value);
    partial void OnWorkPlaceChanged();
    partial void OnWorkNameChanging(string value);
    partial void OnWorkNameChanged();
    partial void OnMaterialCostTotalChanging(System.Nullable<int> value);
    partial void OnMaterialCostTotalChanged();
    partial void OnWorkCostTotalChanging(System.Nullable<int> value);
    partial void OnWorkCostTotalChanged();
    partial void OnOverheadExpenseTotalChanging(System.Nullable<int> value);
    partial void OnOverheadExpenseTotalChanged();
    partial void OnDiscountTotalChanging(System.Nullable<int> value);
    partial void OnDiscountTotalChanged();
    partial void OnAmountTotalChanging(System.Nullable<int> value);
    partial void OnAmountTotalChanged();
    partial void OnAmountRecordedChanging(System.Nullable<int> value);
    partial void OnAmountRecordedChanged();
    partial void OnPaidTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnPaidTimeChanged();
    partial void OnWorkTypeChanging(System.Nullable<char> value);
    partial void OnWorkTypeChanged();
    partial void OnRemarkChanging(string value);
    partial void OnRemarkChanged();
    #endregion
		
		public QuotationSynthetic()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QuotationNoYear", DbType="SmallInt")]
		public System.Nullable<short> QuotationNoYear
		{
			get
			{
				return this._QuotationNoYear;
			}
			set
			{
				if ((this._QuotationNoYear != value))
				{
					this.OnQuotationNoYearChanging(value);
					this.SendPropertyChanging();
					this._QuotationNoYear = value;
					this.SendPropertyChanged("QuotationNoYear");
					this.OnQuotationNoYearChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QuotationNoOrder", DbType="Int")]
		public System.Nullable<int> QuotationNoOrder
		{
			get
			{
				return this._QuotationNoOrder;
			}
			set
			{
				if ((this._QuotationNoOrder != value))
				{
					this.OnQuotationNoOrderChanging(value);
					this.SendPropertyChanging();
					this._QuotationNoOrder = value;
					this.SendPropertyChanged("QuotationNoOrder");
					this.OnQuotationNoOrderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OrderCode", DbType="NVarChar(20)")]
		public string OrderCode
		{
			get
			{
				return this._OrderCode;
			}
			set
			{
				if ((this._OrderCode != value))
				{
					this.OnOrderCodeChanging(value);
					this.SendPropertyChanging();
					this._OrderCode = value;
					this.SendPropertyChanged("OrderCode");
					this.OnOrderCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MadeTime", DbType="Date")]
		public System.Nullable<System.DateTime> MadeTime
		{
			get
			{
				return this._MadeTime;
			}
			set
			{
				if ((this._MadeTime != value))
				{
					this.OnMadeTimeChanging(value);
					this.SendPropertyChanging();
					this._MadeTime = value;
					this.SendPropertyChanged("MadeTime");
					this.OnMadeTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomerName", DbType="NVarChar(50)")]
		public string CustomerName
		{
			get
			{
				return this._CustomerName;
			}
			set
			{
				if ((this._CustomerName != value))
				{
					this.OnCustomerNameChanging(value);
					this.SendPropertyChanging();
					this._CustomerName = value;
					this.SendPropertyChanged("CustomerName");
					this.OnCustomerNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WorkPlace", DbType="NVarChar(50)")]
		public string WorkPlace
		{
			get
			{
				return this._WorkPlace;
			}
			set
			{
				if ((this._WorkPlace != value))
				{
					this.OnWorkPlaceChanging(value);
					this.SendPropertyChanging();
					this._WorkPlace = value;
					this.SendPropertyChanged("WorkPlace");
					this.OnWorkPlaceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WorkName", DbType="NVarChar(50)")]
		public string WorkName
		{
			get
			{
				return this._WorkName;
			}
			set
			{
				if ((this._WorkName != value))
				{
					this.OnWorkNameChanging(value);
					this.SendPropertyChanging();
					this._WorkName = value;
					this.SendPropertyChanged("WorkName");
					this.OnWorkNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaterialCostTotal", DbType="Int")]
		public System.Nullable<int> MaterialCostTotal
		{
			get
			{
				return this._MaterialCostTotal;
			}
			set
			{
				if ((this._MaterialCostTotal != value))
				{
					this.OnMaterialCostTotalChanging(value);
					this.SendPropertyChanging();
					this._MaterialCostTotal = value;
					this.SendPropertyChanged("MaterialCostTotal");
					this.OnMaterialCostTotalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WorkCostTotal", DbType="Int")]
		public System.Nullable<int> WorkCostTotal
		{
			get
			{
				return this._WorkCostTotal;
			}
			set
			{
				if ((this._WorkCostTotal != value))
				{
					this.OnWorkCostTotalChanging(value);
					this.SendPropertyChanging();
					this._WorkCostTotal = value;
					this.SendPropertyChanged("WorkCostTotal");
					this.OnWorkCostTotalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OverheadExpenseTotal", DbType="Int")]
		public System.Nullable<int> OverheadExpenseTotal
		{
			get
			{
				return this._OverheadExpenseTotal;
			}
			set
			{
				if ((this._OverheadExpenseTotal != value))
				{
					this.OnOverheadExpenseTotalChanging(value);
					this.SendPropertyChanging();
					this._OverheadExpenseTotal = value;
					this.SendPropertyChanged("OverheadExpenseTotal");
					this.OnOverheadExpenseTotalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiscountTotal", DbType="Int")]
		public System.Nullable<int> DiscountTotal
		{
			get
			{
				return this._DiscountTotal;
			}
			set
			{
				if ((this._DiscountTotal != value))
				{
					this.OnDiscountTotalChanging(value);
					this.SendPropertyChanging();
					this._DiscountTotal = value;
					this.SendPropertyChanged("DiscountTotal");
					this.OnDiscountTotalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AmountTotal", DbType="Int")]
		public System.Nullable<int> AmountTotal
		{
			get
			{
				return this._AmountTotal;
			}
			set
			{
				if ((this._AmountTotal != value))
				{
					this.OnAmountTotalChanging(value);
					this.SendPropertyChanging();
					this._AmountTotal = value;
					this.SendPropertyChanged("AmountTotal");
					this.OnAmountTotalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AmountRecorded", DbType="Int")]
		public System.Nullable<int> AmountRecorded
		{
			get
			{
				return this._AmountRecorded;
			}
			set
			{
				if ((this._AmountRecorded != value))
				{
					this.OnAmountRecordedChanging(value);
					this.SendPropertyChanging();
					this._AmountRecorded = value;
					this.SendPropertyChanged("AmountRecorded");
					this.OnAmountRecordedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PaidTime", DbType="Date")]
		public System.Nullable<System.DateTime> PaidTime
		{
			get
			{
				return this._PaidTime;
			}
			set
			{
				if ((this._PaidTime != value))
				{
					this.OnPaidTimeChanging(value);
					this.SendPropertyChanging();
					this._PaidTime = value;
					this.SendPropertyChanged("PaidTime");
					this.OnPaidTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WorkType", DbType="Char(1)")]
		public System.Nullable<char> WorkType
		{
			get
			{
				return this._WorkType;
			}
			set
			{
				if ((this._WorkType != value))
				{
					this.OnWorkTypeChanging(value);
					this.SendPropertyChanging();
					this._WorkType = value;
					this.SendPropertyChanged("WorkType");
					this.OnWorkTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Remark", DbType="NVarChar(50)")]
		public string Remark
		{
			get
			{
				return this._Remark;
			}
			set
			{
				if ((this._Remark != value))
				{
					this.OnRemarkChanging(value);
					this.SendPropertyChanging();
					this._Remark = value;
					this.SendPropertyChanged("Remark");
					this.OnRemarkChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MMFee")]
	public partial class MMFee : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _FeeName;
		
		private string _Department;
		
		private string _FeeType;
		
		private string _Item;
		
		private string _Field1;
		
		private string _Field2;
		
		private string _Field3;
		
		private string _Field4;
		
		private string _Field5;
		
		private string _Field6;
		
		private string _Field7;
		
		private string _Field8;
		
		private string _Field9;
		
		private int _Year;
		
		private int _Month4;
		
		private int _Month5;
		
		private int _Month6;
		
		private int _Month7;
		
		private int _Month8;
		
		private int _Month9;
		
		private int _Month10;
		
		private int _Month11;
		
		private int _Month12;
		
		private int _Month1;
		
		private int _Month2;
		
		private int _Month3;
		
		private int _Sum;
		
		private string _Remark;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnFeeNameChanging(string value);
    partial void OnFeeNameChanged();
    partial void OnDepartmentChanging(string value);
    partial void OnDepartmentChanged();
    partial void OnFeeTypeChanging(string value);
    partial void OnFeeTypeChanged();
    partial void OnItemChanging(string value);
    partial void OnItemChanged();
    partial void OnField1Changing(string value);
    partial void OnField1Changed();
    partial void OnField2Changing(string value);
    partial void OnField2Changed();
    partial void OnField3Changing(string value);
    partial void OnField3Changed();
    partial void OnField4Changing(string value);
    partial void OnField4Changed();
    partial void OnField5Changing(string value);
    partial void OnField5Changed();
    partial void OnField6Changing(string value);
    partial void OnField6Changed();
    partial void OnField7Changing(string value);
    partial void OnField7Changed();
    partial void OnField8Changing(string value);
    partial void OnField8Changed();
    partial void OnField9Changing(string value);
    partial void OnField9Changed();
    partial void OnYearChanging(int value);
    partial void OnYearChanged();
    partial void OnMonth4Changing(int value);
    partial void OnMonth4Changed();
    partial void OnMonth5Changing(int value);
    partial void OnMonth5Changed();
    partial void OnMonth6Changing(int value);
    partial void OnMonth6Changed();
    partial void OnMonth7Changing(int value);
    partial void OnMonth7Changed();
    partial void OnMonth8Changing(int value);
    partial void OnMonth8Changed();
    partial void OnMonth9Changing(int value);
    partial void OnMonth9Changed();
    partial void OnMonth10Changing(int value);
    partial void OnMonth10Changed();
    partial void OnMonth11Changing(int value);
    partial void OnMonth11Changed();
    partial void OnMonth12Changing(int value);
    partial void OnMonth12Changed();
    partial void OnMonth1Changing(int value);
    partial void OnMonth1Changed();
    partial void OnMonth2Changing(int value);
    partial void OnMonth2Changed();
    partial void OnMonth3Changing(int value);
    partial void OnMonth3Changed();
    partial void OnSumChanging(int value);
    partial void OnSumChanged();
    partial void OnRemarkChanging(string value);
    partial void OnRemarkChanged();
    #endregion
		
		public MMFee()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FeeName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string FeeName
		{
			get
			{
				return this._FeeName;
			}
			set
			{
				if ((this._FeeName != value))
				{
					this.OnFeeNameChanging(value);
					this.SendPropertyChanging();
					this._FeeName = value;
					this.SendPropertyChanged("FeeName");
					this.OnFeeNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Department", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Department
		{
			get
			{
				return this._Department;
			}
			set
			{
				if ((this._Department != value))
				{
					this.OnDepartmentChanging(value);
					this.SendPropertyChanging();
					this._Department = value;
					this.SendPropertyChanged("Department");
					this.OnDepartmentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FeeType", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string FeeType
		{
			get
			{
				return this._FeeType;
			}
			set
			{
				if ((this._FeeType != value))
				{
					this.OnFeeTypeChanging(value);
					this.SendPropertyChanging();
					this._FeeType = value;
					this.SendPropertyChanged("FeeType");
					this.OnFeeTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Item", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Item
		{
			get
			{
				return this._Item;
			}
			set
			{
				if ((this._Item != value))
				{
					this.OnItemChanging(value);
					this.SendPropertyChanging();
					this._Item = value;
					this.SendPropertyChanged("Item");
					this.OnItemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Field1", DbType="NVarChar(50)")]
		public string Field1
		{
			get
			{
				return this._Field1;
			}
			set
			{
				if ((this._Field1 != value))
				{
					this.OnField1Changing(value);
					this.SendPropertyChanging();
					this._Field1 = value;
					this.SendPropertyChanged("Field1");
					this.OnField1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Field2", DbType="NVarChar(50)")]
		public string Field2
		{
			get
			{
				return this._Field2;
			}
			set
			{
				if ((this._Field2 != value))
				{
					this.OnField2Changing(value);
					this.SendPropertyChanging();
					this._Field2 = value;
					this.SendPropertyChanged("Field2");
					this.OnField2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Field3", DbType="NVarChar(50)")]
		public string Field3
		{
			get
			{
				return this._Field3;
			}
			set
			{
				if ((this._Field3 != value))
				{
					this.OnField3Changing(value);
					this.SendPropertyChanging();
					this._Field3 = value;
					this.SendPropertyChanged("Field3");
					this.OnField3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Field4", DbType="NVarChar(50)")]
		public string Field4
		{
			get
			{
				return this._Field4;
			}
			set
			{
				if ((this._Field4 != value))
				{
					this.OnField4Changing(value);
					this.SendPropertyChanging();
					this._Field4 = value;
					this.SendPropertyChanged("Field4");
					this.OnField4Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Field5", DbType="NVarChar(50)")]
		public string Field5
		{
			get
			{
				return this._Field5;
			}
			set
			{
				if ((this._Field5 != value))
				{
					this.OnField5Changing(value);
					this.SendPropertyChanging();
					this._Field5 = value;
					this.SendPropertyChanged("Field5");
					this.OnField5Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Field6", DbType="NVarChar(50)")]
		public string Field6
		{
			get
			{
				return this._Field6;
			}
			set
			{
				if ((this._Field6 != value))
				{
					this.OnField6Changing(value);
					this.SendPropertyChanging();
					this._Field6 = value;
					this.SendPropertyChanged("Field6");
					this.OnField6Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Field7", DbType="NVarChar(50)")]
		public string Field7
		{
			get
			{
				return this._Field7;
			}
			set
			{
				if ((this._Field7 != value))
				{
					this.OnField7Changing(value);
					this.SendPropertyChanging();
					this._Field7 = value;
					this.SendPropertyChanged("Field7");
					this.OnField7Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Field8", DbType="NVarChar(50)")]
		public string Field8
		{
			get
			{
				return this._Field8;
			}
			set
			{
				if ((this._Field8 != value))
				{
					this.OnField8Changing(value);
					this.SendPropertyChanging();
					this._Field8 = value;
					this.SendPropertyChanged("Field8");
					this.OnField8Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Field9", DbType="NVarChar(50)")]
		public string Field9
		{
			get
			{
				return this._Field9;
			}
			set
			{
				if ((this._Field9 != value))
				{
					this.OnField9Changing(value);
					this.SendPropertyChanging();
					this._Field9 = value;
					this.SendPropertyChanged("Field9");
					this.OnField9Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Year", DbType="Int NOT NULL")]
		public int Year
		{
			get
			{
				return this._Year;
			}
			set
			{
				if ((this._Year != value))
				{
					this.OnYearChanging(value);
					this.SendPropertyChanging();
					this._Year = value;
					this.SendPropertyChanged("Year");
					this.OnYearChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Month4", DbType="Int NOT NULL")]
		public int Month4
		{
			get
			{
				return this._Month4;
			}
			set
			{
				if ((this._Month4 != value))
				{
					this.OnMonth4Changing(value);
					this.SendPropertyChanging();
					this._Month4 = value;
					this.SendPropertyChanged("Month4");
					this.OnMonth4Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Month5", DbType="Int NOT NULL")]
		public int Month5
		{
			get
			{
				return this._Month5;
			}
			set
			{
				if ((this._Month5 != value))
				{
					this.OnMonth5Changing(value);
					this.SendPropertyChanging();
					this._Month5 = value;
					this.SendPropertyChanged("Month5");
					this.OnMonth5Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Month6", DbType="Int NOT NULL")]
		public int Month6
		{
			get
			{
				return this._Month6;
			}
			set
			{
				if ((this._Month6 != value))
				{
					this.OnMonth6Changing(value);
					this.SendPropertyChanging();
					this._Month6 = value;
					this.SendPropertyChanged("Month6");
					this.OnMonth6Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Month7", DbType="Int NOT NULL")]
		public int Month7
		{
			get
			{
				return this._Month7;
			}
			set
			{
				if ((this._Month7 != value))
				{
					this.OnMonth7Changing(value);
					this.SendPropertyChanging();
					this._Month7 = value;
					this.SendPropertyChanged("Month7");
					this.OnMonth7Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Month8", DbType="Int NOT NULL")]
		public int Month8
		{
			get
			{
				return this._Month8;
			}
			set
			{
				if ((this._Month8 != value))
				{
					this.OnMonth8Changing(value);
					this.SendPropertyChanging();
					this._Month8 = value;
					this.SendPropertyChanged("Month8");
					this.OnMonth8Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Month9", DbType="Int NOT NULL")]
		public int Month9
		{
			get
			{
				return this._Month9;
			}
			set
			{
				if ((this._Month9 != value))
				{
					this.OnMonth9Changing(value);
					this.SendPropertyChanging();
					this._Month9 = value;
					this.SendPropertyChanged("Month9");
					this.OnMonth9Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Month10", DbType="Int NOT NULL")]
		public int Month10
		{
			get
			{
				return this._Month10;
			}
			set
			{
				if ((this._Month10 != value))
				{
					this.OnMonth10Changing(value);
					this.SendPropertyChanging();
					this._Month10 = value;
					this.SendPropertyChanged("Month10");
					this.OnMonth10Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Month11", DbType="Int NOT NULL")]
		public int Month11
		{
			get
			{
				return this._Month11;
			}
			set
			{
				if ((this._Month11 != value))
				{
					this.OnMonth11Changing(value);
					this.SendPropertyChanging();
					this._Month11 = value;
					this.SendPropertyChanged("Month11");
					this.OnMonth11Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Month12", DbType="Int NOT NULL")]
		public int Month12
		{
			get
			{
				return this._Month12;
			}
			set
			{
				if ((this._Month12 != value))
				{
					this.OnMonth12Changing(value);
					this.SendPropertyChanging();
					this._Month12 = value;
					this.SendPropertyChanged("Month12");
					this.OnMonth12Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Month1", DbType="Int NOT NULL")]
		public int Month1
		{
			get
			{
				return this._Month1;
			}
			set
			{
				if ((this._Month1 != value))
				{
					this.OnMonth1Changing(value);
					this.SendPropertyChanging();
					this._Month1 = value;
					this.SendPropertyChanged("Month1");
					this.OnMonth1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Month2", DbType="Int NOT NULL")]
		public int Month2
		{
			get
			{
				return this._Month2;
			}
			set
			{
				if ((this._Month2 != value))
				{
					this.OnMonth2Changing(value);
					this.SendPropertyChanging();
					this._Month2 = value;
					this.SendPropertyChanged("Month2");
					this.OnMonth2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Month3", DbType="Int NOT NULL")]
		public int Month3
		{
			get
			{
				return this._Month3;
			}
			set
			{
				if ((this._Month3 != value))
				{
					this.OnMonth3Changing(value);
					this.SendPropertyChanging();
					this._Month3 = value;
					this.SendPropertyChanged("Month3");
					this.OnMonth3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sum", DbType="Int NOT NULL")]
		public int Sum
		{
			get
			{
				return this._Sum;
			}
			set
			{
				if ((this._Sum != value))
				{
					this.OnSumChanging(value);
					this.SendPropertyChanging();
					this._Sum = value;
					this.SendPropertyChanged("Sum");
					this.OnSumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Remark", DbType="NVarChar(50)")]
		public string Remark
		{
			get
			{
				return this._Remark;
			}
			set
			{
				if ((this._Remark != value))
				{
					this.OnRemarkChanging(value);
					this.SendPropertyChanging();
					this._Remark = value;
					this.SendPropertyChanged("Remark");
					this.OnRemarkChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MMSale")]
	public partial class MMSale : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _Department;
		
		private string _Customer;
		
		private int _Year;
		
		private int _Month4;
		
		private int _Month5;
		
		private int _Month6;
		
		private int _Month7;
		
		private int _Month8;
		
		private int _Month9;
		
		private int _Month10;
		
		private int _Month11;
		
		private int _Month12;
		
		private int _Month1;
		
		private int _Month2;
		
		private int _Month3;
		
		private int _Sum;
		
		private string _Remark;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnDepartmentChanging(string value);
    partial void OnDepartmentChanged();
    partial void OnCustomerChanging(string value);
    partial void OnCustomerChanged();
    partial void OnYearChanging(int value);
    partial void OnYearChanged();
    partial void OnMonth4Changing(int value);
    partial void OnMonth4Changed();
    partial void OnMonth5Changing(int value);
    partial void OnMonth5Changed();
    partial void OnMonth6Changing(int value);
    partial void OnMonth6Changed();
    partial void OnMonth7Changing(int value);
    partial void OnMonth7Changed();
    partial void OnMonth8Changing(int value);
    partial void OnMonth8Changed();
    partial void OnMonth9Changing(int value);
    partial void OnMonth9Changed();
    partial void OnMonth10Changing(int value);
    partial void OnMonth10Changed();
    partial void OnMonth11Changing(int value);
    partial void OnMonth11Changed();
    partial void OnMonth12Changing(int value);
    partial void OnMonth12Changed();
    partial void OnMonth1Changing(int value);
    partial void OnMonth1Changed();
    partial void OnMonth2Changing(int value);
    partial void OnMonth2Changed();
    partial void OnMonth3Changing(int value);
    partial void OnMonth3Changed();
    partial void OnSumChanging(int value);
    partial void OnSumChanged();
    partial void OnRemarkChanging(string value);
    partial void OnRemarkChanged();
    #endregion
		
		public MMSale()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Department", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Department
		{
			get
			{
				return this._Department;
			}
			set
			{
				if ((this._Department != value))
				{
					this.OnDepartmentChanging(value);
					this.SendPropertyChanging();
					this._Department = value;
					this.SendPropertyChanged("Department");
					this.OnDepartmentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Customer", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Customer
		{
			get
			{
				return this._Customer;
			}
			set
			{
				if ((this._Customer != value))
				{
					this.OnCustomerChanging(value);
					this.SendPropertyChanging();
					this._Customer = value;
					this.SendPropertyChanged("Customer");
					this.OnCustomerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Year", DbType="Int NOT NULL")]
		public int Year
		{
			get
			{
				return this._Year;
			}
			set
			{
				if ((this._Year != value))
				{
					this.OnYearChanging(value);
					this.SendPropertyChanging();
					this._Year = value;
					this.SendPropertyChanged("Year");
					this.OnYearChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Month4", DbType="Int NOT NULL")]
		public int Month4
		{
			get
			{
				return this._Month4;
			}
			set
			{
				if ((this._Month4 != value))
				{
					this.OnMonth4Changing(value);
					this.SendPropertyChanging();
					this._Month4 = value;
					this.SendPropertyChanged("Month4");
					this.OnMonth4Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Month5", DbType="Int NOT NULL")]
		public int Month5
		{
			get
			{
				return this._Month5;
			}
			set
			{
				if ((this._Month5 != value))
				{
					this.OnMonth5Changing(value);
					this.SendPropertyChanging();
					this._Month5 = value;
					this.SendPropertyChanged("Month5");
					this.OnMonth5Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Month6", DbType="Int NOT NULL")]
		public int Month6
		{
			get
			{
				return this._Month6;
			}
			set
			{
				if ((this._Month6 != value))
				{
					this.OnMonth6Changing(value);
					this.SendPropertyChanging();
					this._Month6 = value;
					this.SendPropertyChanged("Month6");
					this.OnMonth6Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Month7", DbType="Int NOT NULL")]
		public int Month7
		{
			get
			{
				return this._Month7;
			}
			set
			{
				if ((this._Month7 != value))
				{
					this.OnMonth7Changing(value);
					this.SendPropertyChanging();
					this._Month7 = value;
					this.SendPropertyChanged("Month7");
					this.OnMonth7Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Month8", DbType="Int NOT NULL")]
		public int Month8
		{
			get
			{
				return this._Month8;
			}
			set
			{
				if ((this._Month8 != value))
				{
					this.OnMonth8Changing(value);
					this.SendPropertyChanging();
					this._Month8 = value;
					this.SendPropertyChanged("Month8");
					this.OnMonth8Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Month9", DbType="Int NOT NULL")]
		public int Month9
		{
			get
			{
				return this._Month9;
			}
			set
			{
				if ((this._Month9 != value))
				{
					this.OnMonth9Changing(value);
					this.SendPropertyChanging();
					this._Month9 = value;
					this.SendPropertyChanged("Month9");
					this.OnMonth9Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Month10", DbType="Int NOT NULL")]
		public int Month10
		{
			get
			{
				return this._Month10;
			}
			set
			{
				if ((this._Month10 != value))
				{
					this.OnMonth10Changing(value);
					this.SendPropertyChanging();
					this._Month10 = value;
					this.SendPropertyChanged("Month10");
					this.OnMonth10Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Month11", DbType="Int NOT NULL")]
		public int Month11
		{
			get
			{
				return this._Month11;
			}
			set
			{
				if ((this._Month11 != value))
				{
					this.OnMonth11Changing(value);
					this.SendPropertyChanging();
					this._Month11 = value;
					this.SendPropertyChanged("Month11");
					this.OnMonth11Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Month12", DbType="Int NOT NULL")]
		public int Month12
		{
			get
			{
				return this._Month12;
			}
			set
			{
				if ((this._Month12 != value))
				{
					this.OnMonth12Changing(value);
					this.SendPropertyChanging();
					this._Month12 = value;
					this.SendPropertyChanged("Month12");
					this.OnMonth12Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Month1", DbType="Int NOT NULL")]
		public int Month1
		{
			get
			{
				return this._Month1;
			}
			set
			{
				if ((this._Month1 != value))
				{
					this.OnMonth1Changing(value);
					this.SendPropertyChanging();
					this._Month1 = value;
					this.SendPropertyChanged("Month1");
					this.OnMonth1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Month2", DbType="Int NOT NULL")]
		public int Month2
		{
			get
			{
				return this._Month2;
			}
			set
			{
				if ((this._Month2 != value))
				{
					this.OnMonth2Changing(value);
					this.SendPropertyChanging();
					this._Month2 = value;
					this.SendPropertyChanged("Month2");
					this.OnMonth2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Month3", DbType="Int NOT NULL")]
		public int Month3
		{
			get
			{
				return this._Month3;
			}
			set
			{
				if ((this._Month3 != value))
				{
					this.OnMonth3Changing(value);
					this.SendPropertyChanging();
					this._Month3 = value;
					this.SendPropertyChanged("Month3");
					this.OnMonth3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sum", DbType="Int NOT NULL")]
		public int Sum
		{
			get
			{
				return this._Sum;
			}
			set
			{
				if ((this._Sum != value))
				{
					this.OnSumChanging(value);
					this.SendPropertyChanging();
					this._Sum = value;
					this.SendPropertyChanged("Sum");
					this.OnSumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Remark", DbType="NVarChar(50)")]
		public string Remark
		{
			get
			{
				return this._Remark;
			}
			set
			{
				if ((this._Remark != value))
				{
					this.OnRemarkChanging(value);
					this.SendPropertyChanging();
					this._Remark = value;
					this.SendPropertyChanged("Remark");
					this.OnRemarkChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MMRevenue")]
	public partial class MMRevenue : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _Department;
		
		private string _Item;
		
		private string _Sumary;
		
		private int _Year;
		
		private int _Month4;
		
		private int _Month5;
		
		private int _Month6;
		
		private int _Month7;
		
		private int _Month8;
		
		private int _Month9;
		
		private int _Month10;
		
		private int _Month11;
		
		private int _Month12;
		
		private int _Month1;
		
		private int _Month2;
		
		private int _Month3;
		
		private int _Sum;
		
		private string _Remark;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnDepartmentChanging(string value);
    partial void OnDepartmentChanged();
    partial void OnItemChanging(string value);
    partial void OnItemChanged();
    partial void OnSumaryChanging(string value);
    partial void OnSumaryChanged();
    partial void OnYearChanging(int value);
    partial void OnYearChanged();
    partial void OnMonth4Changing(int value);
    partial void OnMonth4Changed();
    partial void OnMonth5Changing(int value);
    partial void OnMonth5Changed();
    partial void OnMonth6Changing(int value);
    partial void OnMonth6Changed();
    partial void OnMonth7Changing(int value);
    partial void OnMonth7Changed();
    partial void OnMonth8Changing(int value);
    partial void OnMonth8Changed();
    partial void OnMonth9Changing(int value);
    partial void OnMonth9Changed();
    partial void OnMonth10Changing(int value);
    partial void OnMonth10Changed();
    partial void OnMonth11Changing(int value);
    partial void OnMonth11Changed();
    partial void OnMonth12Changing(int value);
    partial void OnMonth12Changed();
    partial void OnMonth1Changing(int value);
    partial void OnMonth1Changed();
    partial void OnMonth2Changing(int value);
    partial void OnMonth2Changed();
    partial void OnMonth3Changing(int value);
    partial void OnMonth3Changed();
    partial void OnSumChanging(int value);
    partial void OnSumChanged();
    partial void OnRemarkChanging(string value);
    partial void OnRemarkChanged();
    #endregion
		
		public MMRevenue()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Department", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Department
		{
			get
			{
				return this._Department;
			}
			set
			{
				if ((this._Department != value))
				{
					this.OnDepartmentChanging(value);
					this.SendPropertyChanging();
					this._Department = value;
					this.SendPropertyChanged("Department");
					this.OnDepartmentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Item", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Item
		{
			get
			{
				return this._Item;
			}
			set
			{
				if ((this._Item != value))
				{
					this.OnItemChanging(value);
					this.SendPropertyChanging();
					this._Item = value;
					this.SendPropertyChanged("Item");
					this.OnItemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sumary", DbType="NVarChar(50)")]
		public string Sumary
		{
			get
			{
				return this._Sumary;
			}
			set
			{
				if ((this._Sumary != value))
				{
					this.OnSumaryChanging(value);
					this.SendPropertyChanging();
					this._Sumary = value;
					this.SendPropertyChanged("Sumary");
					this.OnSumaryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Year", DbType="Int NOT NULL")]
		public int Year
		{
			get
			{
				return this._Year;
			}
			set
			{
				if ((this._Year != value))
				{
					this.OnYearChanging(value);
					this.SendPropertyChanging();
					this._Year = value;
					this.SendPropertyChanged("Year");
					this.OnYearChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Month4", DbType="Int NOT NULL")]
		public int Month4
		{
			get
			{
				return this._Month4;
			}
			set
			{
				if ((this._Month4 != value))
				{
					this.OnMonth4Changing(value);
					this.SendPropertyChanging();
					this._Month4 = value;
					this.SendPropertyChanged("Month4");
					this.OnMonth4Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Month5", DbType="Int NOT NULL")]
		public int Month5
		{
			get
			{
				return this._Month5;
			}
			set
			{
				if ((this._Month5 != value))
				{
					this.OnMonth5Changing(value);
					this.SendPropertyChanging();
					this._Month5 = value;
					this.SendPropertyChanged("Month5");
					this.OnMonth5Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Month6", DbType="Int NOT NULL")]
		public int Month6
		{
			get
			{
				return this._Month6;
			}
			set
			{
				if ((this._Month6 != value))
				{
					this.OnMonth6Changing(value);
					this.SendPropertyChanging();
					this._Month6 = value;
					this.SendPropertyChanged("Month6");
					this.OnMonth6Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Month7", DbType="Int NOT NULL")]
		public int Month7
		{
			get
			{
				return this._Month7;
			}
			set
			{
				if ((this._Month7 != value))
				{
					this.OnMonth7Changing(value);
					this.SendPropertyChanging();
					this._Month7 = value;
					this.SendPropertyChanged("Month7");
					this.OnMonth7Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Month8", DbType="Int NOT NULL")]
		public int Month8
		{
			get
			{
				return this._Month8;
			}
			set
			{
				if ((this._Month8 != value))
				{
					this.OnMonth8Changing(value);
					this.SendPropertyChanging();
					this._Month8 = value;
					this.SendPropertyChanged("Month8");
					this.OnMonth8Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Month9", DbType="Int NOT NULL")]
		public int Month9
		{
			get
			{
				return this._Month9;
			}
			set
			{
				if ((this._Month9 != value))
				{
					this.OnMonth9Changing(value);
					this.SendPropertyChanging();
					this._Month9 = value;
					this.SendPropertyChanged("Month9");
					this.OnMonth9Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Month10", DbType="Int NOT NULL")]
		public int Month10
		{
			get
			{
				return this._Month10;
			}
			set
			{
				if ((this._Month10 != value))
				{
					this.OnMonth10Changing(value);
					this.SendPropertyChanging();
					this._Month10 = value;
					this.SendPropertyChanged("Month10");
					this.OnMonth10Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Month11", DbType="Int NOT NULL")]
		public int Month11
		{
			get
			{
				return this._Month11;
			}
			set
			{
				if ((this._Month11 != value))
				{
					this.OnMonth11Changing(value);
					this.SendPropertyChanging();
					this._Month11 = value;
					this.SendPropertyChanged("Month11");
					this.OnMonth11Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Month12", DbType="Int NOT NULL")]
		public int Month12
		{
			get
			{
				return this._Month12;
			}
			set
			{
				if ((this._Month12 != value))
				{
					this.OnMonth12Changing(value);
					this.SendPropertyChanging();
					this._Month12 = value;
					this.SendPropertyChanged("Month12");
					this.OnMonth12Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Month1", DbType="Int NOT NULL")]
		public int Month1
		{
			get
			{
				return this._Month1;
			}
			set
			{
				if ((this._Month1 != value))
				{
					this.OnMonth1Changing(value);
					this.SendPropertyChanging();
					this._Month1 = value;
					this.SendPropertyChanged("Month1");
					this.OnMonth1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Month2", DbType="Int NOT NULL")]
		public int Month2
		{
			get
			{
				return this._Month2;
			}
			set
			{
				if ((this._Month2 != value))
				{
					this.OnMonth2Changing(value);
					this.SendPropertyChanging();
					this._Month2 = value;
					this.SendPropertyChanged("Month2");
					this.OnMonth2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Month3", DbType="Int NOT NULL")]
		public int Month3
		{
			get
			{
				return this._Month3;
			}
			set
			{
				if ((this._Month3 != value))
				{
					this.OnMonth3Changing(value);
					this.SendPropertyChanging();
					this._Month3 = value;
					this.SendPropertyChanged("Month3");
					this.OnMonth3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sum", DbType="Int NOT NULL")]
		public int Sum
		{
			get
			{
				return this._Sum;
			}
			set
			{
				if ((this._Sum != value))
				{
					this.OnSumChanging(value);
					this.SendPropertyChanging();
					this._Sum = value;
					this.SendPropertyChanged("Sum");
					this.OnSumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Remark", DbType="NVarChar(50)")]
		public string Remark
		{
			get
			{
				return this._Remark;
			}
			set
			{
				if ((this._Remark != value))
				{
					this.OnRemarkChanging(value);
					this.SendPropertyChanging();
					this._Remark = value;
					this.SendPropertyChanged("Remark");
					this.OnRemarkChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MMFeeStruct")]
	public partial class MMFeeStruct : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Company;
		
		private string _FeeName;
		
		private string _Field1;
		
		private string _Field2;
		
		private string _Field3;
		
		private string _Field4;
		
		private string _Field5;
		
		private string _Field6;
		
		private string _Field7;
		
		private string _Field8;
		
		private string _Field9;
		
		private string _Remark;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnCompanyChanging(string value);
    partial void OnCompanyChanged();
    partial void OnFeeNameChanging(string value);
    partial void OnFeeNameChanged();
    partial void OnField1Changing(string value);
    partial void OnField1Changed();
    partial void OnField2Changing(string value);
    partial void OnField2Changed();
    partial void OnField3Changing(string value);
    partial void OnField3Changed();
    partial void OnField4Changing(string value);
    partial void OnField4Changed();
    partial void OnField5Changing(string value);
    partial void OnField5Changed();
    partial void OnField6Changing(string value);
    partial void OnField6Changed();
    partial void OnField7Changing(string value);
    partial void OnField7Changed();
    partial void OnField8Changing(string value);
    partial void OnField8Changed();
    partial void OnField9Changing(string value);
    partial void OnField9Changed();
    partial void OnRemarkChanging(string value);
    partial void OnRemarkChanged();
    #endregion
		
		public MMFeeStruct()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Company", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Company
		{
			get
			{
				return this._Company;
			}
			set
			{
				if ((this._Company != value))
				{
					this.OnCompanyChanging(value);
					this.SendPropertyChanging();
					this._Company = value;
					this.SendPropertyChanged("Company");
					this.OnCompanyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FeeName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string FeeName
		{
			get
			{
				return this._FeeName;
			}
			set
			{
				if ((this._FeeName != value))
				{
					this.OnFeeNameChanging(value);
					this.SendPropertyChanging();
					this._FeeName = value;
					this.SendPropertyChanged("FeeName");
					this.OnFeeNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Field1", DbType="NVarChar(50)")]
		public string Field1
		{
			get
			{
				return this._Field1;
			}
			set
			{
				if ((this._Field1 != value))
				{
					this.OnField1Changing(value);
					this.SendPropertyChanging();
					this._Field1 = value;
					this.SendPropertyChanged("Field1");
					this.OnField1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Field2", DbType="NVarChar(50)")]
		public string Field2
		{
			get
			{
				return this._Field2;
			}
			set
			{
				if ((this._Field2 != value))
				{
					this.OnField2Changing(value);
					this.SendPropertyChanging();
					this._Field2 = value;
					this.SendPropertyChanged("Field2");
					this.OnField2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Field3", DbType="NVarChar(50)")]
		public string Field3
		{
			get
			{
				return this._Field3;
			}
			set
			{
				if ((this._Field3 != value))
				{
					this.OnField3Changing(value);
					this.SendPropertyChanging();
					this._Field3 = value;
					this.SendPropertyChanged("Field3");
					this.OnField3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Field4", DbType="NVarChar(50)")]
		public string Field4
		{
			get
			{
				return this._Field4;
			}
			set
			{
				if ((this._Field4 != value))
				{
					this.OnField4Changing(value);
					this.SendPropertyChanging();
					this._Field4 = value;
					this.SendPropertyChanged("Field4");
					this.OnField4Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Field5", DbType="NVarChar(50)")]
		public string Field5
		{
			get
			{
				return this._Field5;
			}
			set
			{
				if ((this._Field5 != value))
				{
					this.OnField5Changing(value);
					this.SendPropertyChanging();
					this._Field5 = value;
					this.SendPropertyChanged("Field5");
					this.OnField5Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Field6", DbType="NVarChar(50)")]
		public string Field6
		{
			get
			{
				return this._Field6;
			}
			set
			{
				if ((this._Field6 != value))
				{
					this.OnField6Changing(value);
					this.SendPropertyChanging();
					this._Field6 = value;
					this.SendPropertyChanged("Field6");
					this.OnField6Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Field7", DbType="NVarChar(50)")]
		public string Field7
		{
			get
			{
				return this._Field7;
			}
			set
			{
				if ((this._Field7 != value))
				{
					this.OnField7Changing(value);
					this.SendPropertyChanging();
					this._Field7 = value;
					this.SendPropertyChanged("Field7");
					this.OnField7Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Field8", DbType="NVarChar(50)")]
		public string Field8
		{
			get
			{
				return this._Field8;
			}
			set
			{
				if ((this._Field8 != value))
				{
					this.OnField8Changing(value);
					this.SendPropertyChanging();
					this._Field8 = value;
					this.SendPropertyChanged("Field8");
					this.OnField8Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Field9", DbType="NVarChar(50)")]
		public string Field9
		{
			get
			{
				return this._Field9;
			}
			set
			{
				if ((this._Field9 != value))
				{
					this.OnField9Changing(value);
					this.SendPropertyChanging();
					this._Field9 = value;
					this.SendPropertyChanged("Field9");
					this.OnField9Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Remark", DbType="NVarChar(50)")]
		public string Remark
		{
			get
			{
				return this._Remark;
			}
			set
			{
				if ((this._Remark != value))
				{
					this.OnRemarkChanging(value);
					this.SendPropertyChanging();
					this._Remark = value;
					this.SendPropertyChanged("Remark");
					this.OnRemarkChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MMFeeMaster")]
	public partial class MMFeeMaster : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _FeeName;
		
		private string _Item;
		
		private string _Field1;
		
		private string _Field2;
		
		private string _Field3;
		
		private string _Field4;
		
		private string _Field5;
		
		private string _Field6;
		
		private string _Field7;
		
		private string _Field8;
		
		private string _Field9;
		
		private bool _HQWork;
		
		private bool _HQ;
		
		private bool _Ota;
		
		private bool _SDC;
		
		private bool _IsFixedFee;
		
		private System.Nullable<System.DateTime> _TimeFrom;
		
		private System.Nullable<System.DateTime> _TimeTo;
		
		private System.Nullable<int> _Amount;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnFeeNameChanging(string value);
    partial void OnFeeNameChanged();
    partial void OnItemChanging(string value);
    partial void OnItemChanged();
    partial void OnField1Changing(string value);
    partial void OnField1Changed();
    partial void OnField2Changing(string value);
    partial void OnField2Changed();
    partial void OnField3Changing(string value);
    partial void OnField3Changed();
    partial void OnField4Changing(string value);
    partial void OnField4Changed();
    partial void OnField5Changing(string value);
    partial void OnField5Changed();
    partial void OnField6Changing(string value);
    partial void OnField6Changed();
    partial void OnField7Changing(string value);
    partial void OnField7Changed();
    partial void OnField8Changing(string value);
    partial void OnField8Changed();
    partial void OnField9Changing(string value);
    partial void OnField9Changed();
    partial void OnHQWorkChanging(bool value);
    partial void OnHQWorkChanged();
    partial void OnHQChanging(bool value);
    partial void OnHQChanged();
    partial void OnOtaChanging(bool value);
    partial void OnOtaChanged();
    partial void OnSDCChanging(bool value);
    partial void OnSDCChanged();
    partial void OnIsFixedFeeChanging(bool value);
    partial void OnIsFixedFeeChanged();
    partial void OnTimeFromChanging(System.Nullable<System.DateTime> value);
    partial void OnTimeFromChanged();
    partial void OnTimeToChanging(System.Nullable<System.DateTime> value);
    partial void OnTimeToChanged();
    partial void OnAmountChanging(System.Nullable<int> value);
    partial void OnAmountChanged();
    #endregion
		
		public MMFeeMaster()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FeeName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string FeeName
		{
			get
			{
				return this._FeeName;
			}
			set
			{
				if ((this._FeeName != value))
				{
					this.OnFeeNameChanging(value);
					this.SendPropertyChanging();
					this._FeeName = value;
					this.SendPropertyChanged("FeeName");
					this.OnFeeNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Item", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Item
		{
			get
			{
				return this._Item;
			}
			set
			{
				if ((this._Item != value))
				{
					this.OnItemChanging(value);
					this.SendPropertyChanging();
					this._Item = value;
					this.SendPropertyChanged("Item");
					this.OnItemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Field1", DbType="NVarChar(50)")]
		public string Field1
		{
			get
			{
				return this._Field1;
			}
			set
			{
				if ((this._Field1 != value))
				{
					this.OnField1Changing(value);
					this.SendPropertyChanging();
					this._Field1 = value;
					this.SendPropertyChanged("Field1");
					this.OnField1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Field2", DbType="NVarChar(50)")]
		public string Field2
		{
			get
			{
				return this._Field2;
			}
			set
			{
				if ((this._Field2 != value))
				{
					this.OnField2Changing(value);
					this.SendPropertyChanging();
					this._Field2 = value;
					this.SendPropertyChanged("Field2");
					this.OnField2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Field3", DbType="NVarChar(50)")]
		public string Field3
		{
			get
			{
				return this._Field3;
			}
			set
			{
				if ((this._Field3 != value))
				{
					this.OnField3Changing(value);
					this.SendPropertyChanging();
					this._Field3 = value;
					this.SendPropertyChanged("Field3");
					this.OnField3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Field4", DbType="NVarChar(50)")]
		public string Field4
		{
			get
			{
				return this._Field4;
			}
			set
			{
				if ((this._Field4 != value))
				{
					this.OnField4Changing(value);
					this.SendPropertyChanging();
					this._Field4 = value;
					this.SendPropertyChanged("Field4");
					this.OnField4Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Field5", DbType="NVarChar(50)")]
		public string Field5
		{
			get
			{
				return this._Field5;
			}
			set
			{
				if ((this._Field5 != value))
				{
					this.OnField5Changing(value);
					this.SendPropertyChanging();
					this._Field5 = value;
					this.SendPropertyChanged("Field5");
					this.OnField5Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Field6", DbType="NVarChar(50)")]
		public string Field6
		{
			get
			{
				return this._Field6;
			}
			set
			{
				if ((this._Field6 != value))
				{
					this.OnField6Changing(value);
					this.SendPropertyChanging();
					this._Field6 = value;
					this.SendPropertyChanged("Field6");
					this.OnField6Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Field7", DbType="NVarChar(50)")]
		public string Field7
		{
			get
			{
				return this._Field7;
			}
			set
			{
				if ((this._Field7 != value))
				{
					this.OnField7Changing(value);
					this.SendPropertyChanging();
					this._Field7 = value;
					this.SendPropertyChanged("Field7");
					this.OnField7Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Field8", DbType="NVarChar(50)")]
		public string Field8
		{
			get
			{
				return this._Field8;
			}
			set
			{
				if ((this._Field8 != value))
				{
					this.OnField8Changing(value);
					this.SendPropertyChanging();
					this._Field8 = value;
					this.SendPropertyChanged("Field8");
					this.OnField8Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Field9", DbType="NVarChar(50)")]
		public string Field9
		{
			get
			{
				return this._Field9;
			}
			set
			{
				if ((this._Field9 != value))
				{
					this.OnField9Changing(value);
					this.SendPropertyChanging();
					this._Field9 = value;
					this.SendPropertyChanged("Field9");
					this.OnField9Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HQWork", DbType="Bit NOT NULL")]
		public bool HQWork
		{
			get
			{
				return this._HQWork;
			}
			set
			{
				if ((this._HQWork != value))
				{
					this.OnHQWorkChanging(value);
					this.SendPropertyChanging();
					this._HQWork = value;
					this.SendPropertyChanged("HQWork");
					this.OnHQWorkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HQ", DbType="Bit NOT NULL")]
		public bool HQ
		{
			get
			{
				return this._HQ;
			}
			set
			{
				if ((this._HQ != value))
				{
					this.OnHQChanging(value);
					this.SendPropertyChanging();
					this._HQ = value;
					this.SendPropertyChanged("HQ");
					this.OnHQChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ota", DbType="Bit NOT NULL")]
		public bool Ota
		{
			get
			{
				return this._Ota;
			}
			set
			{
				if ((this._Ota != value))
				{
					this.OnOtaChanging(value);
					this.SendPropertyChanging();
					this._Ota = value;
					this.SendPropertyChanged("Ota");
					this.OnOtaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDC", DbType="Bit NOT NULL")]
		public bool SDC
		{
			get
			{
				return this._SDC;
			}
			set
			{
				if ((this._SDC != value))
				{
					this.OnSDCChanging(value);
					this.SendPropertyChanging();
					this._SDC = value;
					this.SendPropertyChanged("SDC");
					this.OnSDCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsFixedFee", DbType="Bit NOT NULL")]
		public bool IsFixedFee
		{
			get
			{
				return this._IsFixedFee;
			}
			set
			{
				if ((this._IsFixedFee != value))
				{
					this.OnIsFixedFeeChanging(value);
					this.SendPropertyChanging();
					this._IsFixedFee = value;
					this.SendPropertyChanged("IsFixedFee");
					this.OnIsFixedFeeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TimeFrom", DbType="Date")]
		public System.Nullable<System.DateTime> TimeFrom
		{
			get
			{
				return this._TimeFrom;
			}
			set
			{
				if ((this._TimeFrom != value))
				{
					this.OnTimeFromChanging(value);
					this.SendPropertyChanging();
					this._TimeFrom = value;
					this.SendPropertyChanged("TimeFrom");
					this.OnTimeFromChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TimeTo", DbType="Date")]
		public System.Nullable<System.DateTime> TimeTo
		{
			get
			{
				return this._TimeTo;
			}
			set
			{
				if ((this._TimeTo != value))
				{
					this.OnTimeToChanging(value);
					this.SendPropertyChanging();
					this._TimeTo = value;
					this.SendPropertyChanged("TimeTo");
					this.OnTimeToChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Amount", DbType="Int")]
		public System.Nullable<int> Amount
		{
			get
			{
				return this._Amount;
			}
			set
			{
				if ((this._Amount != value))
				{
					this.OnAmountChanging(value);
					this.SendPropertyChanging();
					this._Amount = value;
					this.SendPropertyChanged("Amount");
					this.OnAmountChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MMFeeTypeStruct")]
	public partial class MMFeeTypeStruct : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private int _FeeId;
		
		private string _FeeType;
		
		private string _Remark;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnFeeIdChanging(int value);
    partial void OnFeeIdChanged();
    partial void OnFeeTypeChanging(string value);
    partial void OnFeeTypeChanged();
    partial void OnRemarkChanging(string value);
    partial void OnRemarkChanged();
    #endregion
		
		public MMFeeTypeStruct()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FeeId", DbType="Int NOT NULL")]
		public int FeeId
		{
			get
			{
				return this._FeeId;
			}
			set
			{
				if ((this._FeeId != value))
				{
					this.OnFeeIdChanging(value);
					this.SendPropertyChanging();
					this._FeeId = value;
					this.SendPropertyChanged("FeeId");
					this.OnFeeIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FeeType", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string FeeType
		{
			get
			{
				return this._FeeType;
			}
			set
			{
				if ((this._FeeType != value))
				{
					this.OnFeeTypeChanging(value);
					this.SendPropertyChanging();
					this._FeeType = value;
					this.SendPropertyChanged("FeeType");
					this.OnFeeTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Remark", DbType="NVarChar(50)")]
		public string Remark
		{
			get
			{
				return this._Remark;
			}
			set
			{
				if ((this._Remark != value))
				{
					this.OnRemarkChanging(value);
					this.SendPropertyChanging();
					this._Remark = value;
					this.SendPropertyChanged("Remark");
					this.OnRemarkChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
